### PR TITLE
MONOCULAR DEPTH ESTIMATION USING RGB IMAGES

### PR DESCRIPTION
**Pull request by vaibhawkhemka**
### DepthEstimation Component
The component takes frames from the camera as input and predicts the depth of each pixel in the frame as output.
### DepthEstimationClient Component
The component uses _DepthEstimation_ and _camerasimple_ for building **DepthMap** using depth of the frames.

### CODE REVIEW

**Comment by vaibhawkhemka** [comment]
Please review this @orensbruli @pbustos

**Comment by orensbruli** [comment]
Robocomp interface related with this PR https://github.com/robocomp/robocomp/pull/329

**Comment by DarkGeekMS** [comment]
@vaibhawkhemka 
Please transfer the PR to [DNN-Services](https://github.com/robocomp/DNN-Services) repo under `components/`, 
as it will be the main repo for this project.

**Comment by vaibhawkhemka** [comment]
@DarkGeekMS  Should I add both **DepthEstimation** for calculating depths and **DepthEstimationClient** for generating DepthMap?

**Comment by DarkGeekMS** [comment]
> @DarkGeekMS Should I add both **DepthEstimation** for calculating depths and **DepthEstimationClient** for generating DepthMap?

It really depends on your design and approach, which we should talk about.
However, any work related to monocular depth estimation project should be on DNN-Services repo mainly.

**Comment by DarkGeekMS** [comment]
@vaibhawkhemka 
Since the PR is transferred to DNN-Services repo, this one is now redundant.
So, please close it.

**Pull request closed without merging**
