### PR TITLE
Hand Bounding Box detection component

### PR DESCRIPTION
**Pull request by Kanav-7**
This PR adds the following to the roboloab functionalities:

- cdsl definitions and directories for handGestureClient, handKeypoint and handGesture
-  handGestureClient that takes an image as input (from camerasimple) and finds the bounding box of the hand in the image.

### CODE REVIEW

**Comment by orensbruli** [comment]
Please, review if the files in the build directory of your component are really needed in the repository.

**Comment by Kanav-7** [comment]
@orensbruli I have removed the unused files

**Comment by orensbruli** [comment]
Ok, I have taken a deeper look into your commit. All your code is located in the build directory. That directory inside a component is usually created only to compile and build and it usually contains autogenerated and removable files. In my opinion, what you have in build should be directly in the component directory (the parent of "build").

**Comment by Kanav-7** [comment]
@orensbruli made the required changes. Do let me know whether it is fine now or not.

**Pull request merged**
